
@startuml

actor Alumno as al
usecase PM as "Pagar matrícula"
usecase EB as "Elegir becas"
usecase RP as "Rellenar datos personales"
usecase ED as "Elegir grupo docente"
usecase ET as "Elegir grupo de trabajo"
usecase EA as "Elegir asignaturas"
usecase IS as "Iniciar sesión automatrícula"
usecase EP as "Elegir plan de estudios"
usecase TB as "Tener beca"
al -- IS
IS ..> EP#line.dashed;text:black : <<include>>
IS ..> RP#line.dashed;text:black : <<include>>
IS ..> EA#line.dashed;text:black : <<include>>
IS ..> TB#line.dashed;text:black : <<include>>
IS ..> PM#line.dashed;text:black : <<include>>
PM ..> (Elegir plan de pago)#line.dashed;text:black : <<include>>
PM ..> (Añadir cuenta bancaria)#line.dashed;text:black : <<include>>
TB ..> EB#line.dashed;text:black : <<include>>
EA ..> ED#line.dashed;text:black : <<include>>
ED ..> ET#line.dashed;text:black : <<include>>

@enduml