@startuml

"Comprador" as comprador
"Vendedor" as vendedor
"Administrador" as administrador
"Proveedor" as proveedor

comprador --> (Agregar producto)
(Agregar producto).>(Marcar como bloqueado)
comprador --> (Consultar precio)
comprador --> (Finalizar compra)
comprador --> (Consultar compra)
@enduml